### ISSUE TITLE
这个插件加载之后怎么样才能看到效果？

### ISSUE THREAD

**Issue by lovelyjuice** [j1anFen/burp_jspath#2]
![image](https://user-images.githubusercontent.com/20644461/72503780-81502b80-3877-11ea-9617-59a5b1116426.png)
Proxy已经走流量了，而且HTML的内联脚本中确实是有接口地址的

**Comment by j1anFen** [comment]
是什么样的接口，我看看为啥没匹配到。不保存文件，会显示在输出界面上。

**Comment by lovelyjuice** [comment]
后面不知道怎么就能用了，可能是我当时的操作有问题
